# **Computational Methods Assignment 3**
#### S.M.T.N. Samarathunge
#### E/19/346
#### EM 317

###**Task 01**

(a) Find the PLU factorization (PA = LU) of the matrix A, using Gaussian elimination with partial pivoting.
                    

\begin{equation*}
    A = \begin{bmatrix}
        -2 & 0 & 1 & -1 \\
        -1 & 2 & 0 & 1 \\
        4 & -1 & -2 & -4 \\
        0 & 0 & 2 & 0
    \end{bmatrix}
\end{equation*}




$$
\begin{bmatrix}
    1 & 0 & 0 & 0 \\
    0 & 1 & 0 & 0 \\
    0 & 0 & 1 & 0 \\
    0 & 0 & 0 & 1 \\
\end{bmatrix}
\times
\begin{bmatrix}
    -2 & 0 &1 & -1 \\
    -1 & 2 & 0 & 1 \\
    4 & -1 & -2 & -4 \\
    0 & 0 & 2 & 0 \\
\end{bmatrix}
:P=>
\begin{bmatrix}
    1 & 0 & 0 & 0 \\
    0 & 1 & 0 & 0 \\
    0 & 0 & 1 & 0 \\
    0 & 0 & 0 & 1 \\
\end{bmatrix}
$$
<br>
Interchanging R1 and R3,
<br>
$$
\begin{bmatrix}
    1 & 0 & 0 & 0 \\
    0 & 1 & 0 & 0 \\
    0 & 0 & 1 & 0 \\
    0 & 0 & 0 & 1 \\
\end{bmatrix}
\times
\begin{bmatrix}
    4 & -1 & -2 & -4 \\
    -1 & 2 & 0 & 1 \\
    -2 & 0 &1 & -1 \\
    0 & 0 & 2 & 0 \\
\end{bmatrix}
:P=>
\begin{bmatrix}
    0 & 0 & 1 & 0 \\
    0 & 1 & 0 & 0 \\
    1 & 0 & 0 & 0 \\
    0 & 0 & 0 & 1 \\
\end{bmatrix}
$$
<br>
Substituting R2 by R2 → R2 - (-1/4) * R1 and R3 by R3 → R3 - (-1/2) * R1,
<br>

$$
\begin{bmatrix}
    1 & 0 & 0 & 0 \\
    -\frac{1}{4} & 1 & 0 & 0 \\
    -\frac{1}{2} & 0 & 1 & 0 \\
    0 & 0 & 0 & 1 \\
\end{bmatrix}
\times
\begin{bmatrix}
    4 & -1 & -2 & -4 \\
    0 & \frac{7}{4} & -\frac{1}{2} & 0 \\
    0 & -\frac{1}{2} & 0 & -3 \\
    0 & 0 & 2 & 0 \\
\end{bmatrix}
:P=>
\begin{bmatrix}
    0 & 0 & 1 & 0 \\
    0 & 1 & 0 & 0 \\
    1 & 0 & 0 & 0 \\
    0 & 0 & 0 & 1 \\
\end{bmatrix}
$$
<br>
Substituting R3 by R3 → R3 - (-2/7) * R2,
<br>

$$
\begin{bmatrix}
    1 & 0 & 0 & 0 \\
    -\frac{1}{4} & 1 & 0 & 0 \\
    -\frac{1}{2} & -\frac{2}{7} & 1 & 0 \\
    0 & 0 & 0 & 1 \\
\end{bmatrix}
\times
\begin{bmatrix}
    4 & -1 & -2 & -4 \\
    0 & \frac{7}{4} & -\frac{1}{2} & 0 \\
    0 & 0 & -\frac{1}{7} & -3 \\
    0 & 0 & 2 & 0 \\
\end{bmatrix}
:P=>
\begin{bmatrix}
    0 & 0 & 1 & 0 \\
    0 & 1 & 0 & 0 \\
    1 & 0 & 0 & 0 \\
    0 & 0 & 0 & 1 \\
\end{bmatrix}
$$
<br>
Interchanging R3 and R4,
<br>

$$
\begin{bmatrix}
    1 & 0 & 0 & 0 \\
    -\frac{1}{4} & 1 & 0 & 0 \\
    0 & 0 & 1 & 0 \\
    -\frac{1}{2} & -\frac{2}{7} & 0 & 1 \\
\end{bmatrix}
\times
\begin{bmatrix}
    4 & -1 & -2 & -4 \\
    0 & \frac{7}{4} & -\frac{1}{2} & 0 \\
    0 & 0 & 2 & 0 \\
    0 & 0 & \frac{1}{7} & -3 \\
\end{bmatrix}
:P=>
\begin{bmatrix}
    0 & 0 & 1 & 0 \\
    0 & 1 & 0 & 0 \\
    0 & 0 & 0 & 1 \\
    1 & 0 & 0 & 0 \\
\end{bmatrix}
$$
<br>
Substituting R4 by R4 → R4 - (-1/14) * R3,
<br>

$$
\begin{bmatrix}
    1 & 0 & 0 & 0 \\
    -\frac{1}{4} & 1 & 0 & 0 \\
    0 & 0 & 1 & 0 \\
    -\frac{1}{2} & -\frac{2}{7} &  -\frac{1}{14} & 1 \\
\end{bmatrix}
\times
\begin{bmatrix}
    4 & -1 & -2 & -4 \\
    0 & \frac{7}{4} & -\frac{1}{2} & 0 \\
    0 & 0 & 2 & 0 \\
    0 & 0 & 0 & -3 \\
\end{bmatrix}
:P=>
\begin{bmatrix}
    0 & 0 & 1 & 0 \\
    0 & 1 & 0 & 0 \\
    0 & 0 & 0 & 1 \\
    1 & 0 & 0 & 0 \\
\end{bmatrix}
$$

\begin{equation*}
    P = \begin{bmatrix}
        0 & 0 & 1 & 0 \\
        0 & 1 & 0 & 0 \\
        0 & 0 & 0 & 1 \\
        1 & 0 & 0 & 0
    \end{bmatrix}
\end{equation*}

\begin{equation*}
    L = \begin{bmatrix}
        1 & 0 & 0 & 0 \\
        -0.25 & 1 & 0 & 0 \\
        0 & 0 & 1 & 0 \\
        -0.5 & -0.2857 & -0.0714 & 1
    \end{bmatrix}
\end{equation*}

\begin{equation*}
    U = \begin{bmatrix}
        4 & -1 & -2 & -4 \\
        0 & 1.75 & -0.5 & 0 \\
        0 & 0 & 2 & 0 \\
        0 & 0 & 0 & -3
    \end{bmatrix}
\end{equation*}


(b)	Use the PLU factorization and forward and back substitution to solve the linear system Ax =b, with b = [1,0,1,0]t.

\begin{align*}
Ax = b\\
PAx = Pb\\
LUx = Pb\\
Ly = Pb
\end{align*}


\begin{equation*}
    b = \begin{bmatrix}
        1 \\
        0 \\
        1 \\
        0
    \end{bmatrix}
\end{equation*}


$$
Pb=\begin{bmatrix}
    0 &0 &1 &0 \\
    0 &1 &0 &0 \\
    0 &0 &0 &1 \\
    1 &0 &0 &0
\end{bmatrix}
\times
\begin{bmatrix}
    1 \\
    0 \\
    1 \\
    0
\end{bmatrix}
$$

$$
Pb=\begin{bmatrix}
    1 \\
    0 \\
    0 \\
    1
\end{bmatrix}
$$

$$
\begin{bmatrix}
    1 & 0 & 0 & 0 \\
    -\frac{1}{4} & 1 & 0 & 0 \\
    0 & 0 & 1 & 0 \\
    -\frac{1}{2} & -\frac{2}{7} & -\frac{1}{14} & 1 \\
\end{bmatrix}
\times
\begin{bmatrix}
    y_{1}  \\
    y_{2}  \\
    y_{3} \\
    y_{4} \\
\end{bmatrix}
=
\begin{bmatrix}
    1 \\
    0 \\
    0 \\
    1
\end{bmatrix}
$$
<br>
\begin{align*}
y_1 = 1\\
y_3 = 0\\
-\frac{1}{4}y_1 + y_2 = 0\\
y_2 = \frac{1}{4}\\
-\frac{1}{2}y_1 - \frac{2}{7}y_2 - \frac{1}{14}y_3 + y_4 = 1\\
y_4 = \frac{11}{7}
\end{align*}
<br>

$$
y=\begin{bmatrix}
    1 \\
    \frac{1}{4} \\
    0 \\
    \frac{11}{7}
\end{bmatrix}
$$
<br>
\begin{align*}
Ux = y
\end{align*}
<br>

$$
\begin{bmatrix}
    4 & -1 & -2 & -4 \\
    0 & \frac{7}{4} & -\frac{1}{2} & 0 \\
    0 & 0 & 2 & 0 \\
    0 & 0 & 0 & -3 \\
\end{bmatrix}
\times
\begin{bmatrix}
    x_{1}  \\
    x_{2}  \\
    x_{3} \\
    x_{4} \\
\end{bmatrix}
=
\begin{bmatrix}
    1 \\
    \frac{1}{4} \\
    0 \\
    \frac{11}{7}
\end{bmatrix}
$$
<br>
\begin{align*}
-3x_4 = \frac{11}{7}\\
x_4 = -\frac{11}{21}\\
x_3 = 0\\
\frac{7}{4}x_2 - \frac{1}{2}x_3 = \frac{1}{4}\\
x_2 = \frac{1}{7}\\
4x_1 - x_2 - 2x_3 - 4x_4 = 1\\
x_1 = -\frac{5}{21}
\end{align*}
<br>
$$
y=\begin{bmatrix}
    -\frac{5}{21} \\
    \frac{1}{7} \\
    0 \\
    -\frac{11}{21}
\end{bmatrix}
$$

In [1]:
#(a) Find the PLU factorization (PA = LU) of the matrix using Gaussian elimination with partial pivoting.

import numpy as np
from scipy.linalg import lu

# Define a matrix
A = np.array([[-2, 0,1, -1], [-1,2, 0, 1], [4,-1, -2, -4],[0,0,2,0]])

# Perform PLU factorization
P, L, U = lu(A)

print("Answer for (a):")
print("Matrix P:")
print(P)
print("Matrix L:")
print(L)
print("Matrix U:")
print(U)


Answer for (a):
Matrix P:
[[0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]]
Matrix L:
[[ 1.          0.          0.          0.        ]
 [-0.25        1.          0.          0.        ]
 [ 0.          0.          1.          0.        ]
 [-0.5        -0.28571429 -0.07142857  1.        ]]
Matrix U:
[[ 4.   -1.   -2.   -4.  ]
 [ 0.    1.75 -0.5   0.  ]
 [ 0.    0.    2.    0.  ]
 [ 0.    0.    0.   -3.  ]]


###**Task 02**

In [2]:
A = [[1.2969,0.8648],[0.2161,0.1441]]
b = [0.8642,0.1440]

x = [2,-2]

#(a) Show that x = [2,-2] is a solution to Ax = b
# Verifying Ax becomes b when x is [2,-2]t

print("A*x = b:")
print(np.dot(A,x))
print("b:")
print(b)

x1 = [0,1]
x2 = [0.9911,-0.4870]

#(b) Compute the error and residual vectors for x1 and x2

print("x1:")
print(x1)
print("x2:")
print(x2)
print("A*x1 = b:")
print(np.dot(A,x1))
print("A*x2 = b:")
print(np.dot(A,x2))
print("b:")
print(b)
# Error
print("Error x1:")
print(np.subtract(x1,x))
print("Error x2:")
print(np.subtract(x2,x))
# Residual
print("Residual x1:")
print(np.subtract(b,np.dot(A,x1)))
print("Residual x2:")
print(np.subtract(b,np.dot(A,x2)))

#(c) find ||A||_inf and ||A^-1||_inf and the condition number of k_inf(A)

print("||A||_inf:")
print(np.linalg.norm(A,ord=np.inf))
print("||A^-1||_inf:")
print(np.linalg.norm(np.linalg.inv(A),ord=np.inf))
print("Condition number:")
print(np.linalg.norm(A,ord=np.inf)*np.linalg.norm(np.linalg.inv(A),ord=np.inf))

A*x = b:
[0.8642 0.144 ]
b:
[0.8642, 0.144]
x1:
[0, 1]
x2:
[0.9911, -0.487]
A*x1 = b:
[0.8648 0.1441]
A*x2 = b:
[0.86419999 0.14400001]
b:
[0.8642, 0.144]
Error x1:
[-2  3]
Error x2:
[-1.0089  1.513 ]
Residual x1:
[-0.0006 -0.0001]
Residual x2:
[ 1.00000001e-08 -9.99999999e-09]
||A||_inf:
2.1616999999999997
||A^-1||_inf:
151300000.2352261
Condition number:
327065210.50848824


###**Task 03**

In [3]:
#(a)

def jacobi_iteration_matrix(A):
    D = np.diag(np.diag(A))
    L = -np.tril(A, k=-1)
    U = -np.triu(A, k=1)
    inv_D = np.linalg.inv(D)
    TJ = np.dot(inv_D, L + U)
    return TJ

def gauss_seidel_iteration_matrix(A):
    D = np.diag(np.diag(A))
    L = -np.tril(A, k=-1)
    U = -np.triu(A, k=1)
    D_L_inv = np.linalg.inv(D + L)
    TGS = np.dot(D_L_inv, U)
    return TGS

# Given matrix A
A = np.array([[4, 1], [1, 4]])

b = [5,5]


# Calculate Jacobi and Gauss-Seidel iteration matrices
TJ = jacobi_iteration_matrix(A)
TGS = gauss_seidel_iteration_matrix(A)

# Print the results
print("Jacobi Iteration Matrix (TJ):")
print(TJ)

print("\nGauss-Seidel Iteration Matrix (TGS):")
print(TGS)

#(b)

#Find infinity norm of TJ and TGS
print("Infinity norm of TJ:")
print(np.linalg.norm(TJ,ord=np.inf))
print("Infinity norm of TGS:")
print(np.linalg.norm(TGS,ord=np.inf))

#Find the spectral radius of TJ and TGS
print("Spectral radius of TJ:")
print(max(abs(np.linalg.eigvals(TJ))))
print("Spectral radius of TGS:")
print(max(abs(np.linalg.eigvals(TGS))))

Jacobi Iteration Matrix (TJ):
[[ 0.   -0.25]
 [-0.25  0.  ]]

Gauss-Seidel Iteration Matrix (TGS):
[[ 0.     -0.25  ]
 [ 0.     -0.0625]]
Infinity norm of TJ:
0.25
Infinity norm of TGS:
0.25
Spectral radius of TJ:
0.25
Spectral radius of TGS:
0.0625


In [4]:
#(c)

#Jacobi method
import numpy as np

def J(A, b, x):
    A = np.array(A)
    n = len(A)
    InvD = np.zeros([n, n])
    R = A
    for i in range(n):
        InvD[i, i] = 1 / A[i, i]
        R[i, i] = 0
    return np.matmul(InvD, (b - np.matmul(R, x)))

A = [[4, 1], [1, 4]]
b = [5, 5]
x = [[0, 0]]
MaxIter = 5
ErrorTable = [1]
ErrorRatio = [0]
eps = 0.001
i = 1

while i <= MaxIter and abs(ErrorTable[i - 1]) > eps:
    xi = J(A, b, x[i - 1])
    x.append(xi)
    ei = np.linalg.norm(x[i] - x[i - 1], np.inf)  # /np.linalg.norm(x[i],np.inf)
    ErrorTable.append(ei)
    zi = np.linalg.norm(x[i] - x[i - 1], np.inf) / np.linalg.norm(x[i - 1] - x[i - 2], np.inf)
    ErrorRatio.append(zi)
    i += 1

print("Solution: Jacobi method")
'''
column 1: k (iteration step)
column 2: (1st component of computed solution vector at step k)
column 3: (2nd component of computed solution vector at step k)
column 4: ke(k)k∞ (error norm at step k)
column 5: ke(k)k∞/ke(k−1)k∞ (ratio of successive error norms at step k)

'''
from tabulate import tabulate

table = []
for i in range(len(x)):
    table.append([i, x[i][0], x[i][1], ErrorTable[i], ErrorRatio[i]])

print(tabulate(table, headers=["k", "x1", "x2", "ke(k)k∞", "ke(k)k∞/ke(k−1)k∞"]))

Solution: Jacobi method
  k        x1        x2     ke(k)k∞    ke(k)k∞/ke(k−1)k∞
---  --------  --------  ----------  -------------------
  0  0         0         1                          0
  1  1.25      1.25      1.25                       1
  2  0.9375    0.9375    0.3125                     0.25
  3  1.01562   1.01562   0.078125                   0.25
  4  0.996094  0.996094  0.0195312                  0.25
  5  1.00098   1.00098   0.00488281                 0.25


In [5]:
#Gauss Siedel Method
from numpy import linalg
def GS(A, b, x):
  A = np.array(A)
  n = len(A)
  xnew = np.zeros(n)
  for i in range(n):
    xnew[i] = (b[i] - sum([A[i, j]*x[j] for j in range(i+1, n)]) - sum([A[i, j]*xnew[j] for j in range(i)]))/A[i, i]
  return xnew

A = [[4, 1], [1, 4]]
b = [5,5]
x = [[0, 0]]
MaxIter = 100
ErrorTable = [1]
ErrorRatio =[0]
eps = 0.001
i = 1

while i <= MaxIter and abs(ErrorTable[i - 1]) > eps:
  xi = GS(A, b, x[i - 1])
  x.append(xi)
 # ei = np.linalg.norm(x[i] - x[i - 1])/np.linalg.norm(x[i])
  ei=np.linalg.norm(x[i]-x[i-1],np.inf)#/np.linalg.norm(x[i],np.inf)
  ErrorTable.append(ei)
  zi = np.linalg.norm(x[i] - x[i - 1], np.inf) / np.linalg.norm(x[i - 1] - x[i - 2], np.inf)
  ErrorRatio.append(zi)
  i+=1
# Gause Seidel Solution
print("Solution: Gauss-Seidel method")
'''
column 1: k (iteration step)
column 2: (1st component of computed solution vector at step k)
column 3: (2nd component of computed solution vector at step k)
column 4: ke(k)k∞ (error norm at step k)
column 5: ke(k)k∞/ke(k−1)k∞ (ratio of successive error norms at step k)

'''

from tabulate import tabulate

table = []
for i in range(len(x)):
    table.append([i, x[i][0], x[i][1], ErrorTable[i], ErrorRatio[i]])

print(tabulate(table, headers=["k", "x1", "x2", "ke(k)k∞", "ke(k)k∞/ke(k−1)k∞"]))

Solution: Gauss-Seidel method
  k       x1        x2      ke(k)k∞    ke(k)k∞/ke(k−1)k∞
---  -------  --------  -----------  -------------------
  0  0        0         1                         0
  1  1.25     0.9375    1.25                      1
  2  1.01562  0.996094  0.234375                  0.1875
  3  1.00098  0.999756  0.0146484                 0.0625
  4  1.00006  0.999985  0.000915527               0.0625


#### **Which method converges faster? Why?**
##### Gauss-Seidel converges faster than Jacobi, because Gauss-Seidel uses the most recent values of the iterates to compute the next iterate, while Jacobi uses the previous values of the iterates to compute the next iterate.

###**Task 04**

In [6]:
A = [[2,-1,1],[2,2,2],[-1,-1,2]]

#(a) is the coefficient matrix A diagonally dominant?

# Define a function to check if a matrix is diagonally dominant
def is_diagonally_dominant(A):
    # Get the diagonal elements
    D = np.diag(np.abs(A))
    # Sum the rows without diagonal elements
    S = np.sum(np.abs(A), axis=1) - D
    # Compare the diagonal elements with the row sums
    if np.all(D > S):
        print("A is diagonally dominant")
    else:
        print("A is not diagonally dominant")

# Check if A is diagonally dominant
is_diagonally_dominant(A)

#(b) find Tj and TGS

print("TJ:")
print(jacobi_iteration_matrix(A))
print("TGS:")
print(gauss_seidel_iteration_matrix(A))

#(c) find the spectral radius of Tj and TGS

print("Spectral radius of TJ:")
print(max(abs(np.linalg.eigvals(jacobi_iteration_matrix(A)))))
print("Spectral radius of TGS:")
print(max(abs(np.linalg.eigvals(gauss_seidel_iteration_matrix(A)))))

# find the infinity norm of Tj and TGS

print("Infinity norm of TJ:")
print(np.linalg.norm(jacobi_iteration_matrix(A),ord=np.inf))
print("Infinity norm of TGS:")
print(np.linalg.norm(gauss_seidel_iteration_matrix(A),ord=np.inf))





A is not diagonally dominant
TJ:
[[ 0.   0.5 -0.5]
 [-1.   0.  -1. ]
 [ 0.5  0.5  0. ]]
TGS:
[[ 0.   0.5 -0.5]
 [ 0.   0.5 -1.5]
 [ 0.  -0.5  1. ]]
Spectral radius of TJ:
1.1180339887498956
Spectral radius of TGS:
1.6513878188659974
Infinity norm of TJ:
2.0
Infinity norm of TGS:
2.0


####  **(d) What can you say about the convergence of the problem with respect to Jacobi and Gauss seidel iteration?**
##### Since matrix A is not diagonally dominant, Jacobi iteations will not converge to a solution whereas the Gauss Siedel Method will converge to a solution.

In [7]:
#(e)
#Jacobi method
import numpy as np

def J(A, b, x):
    A = np.array(A)
    n = len(A)
    InvD = np.zeros([n, n])
    R = A
    for i in range(n):
        InvD[i, i] = 1 / A[i, i]
        R[i, i] = 0
    return np.matmul(InvD, (b - np.matmul(R, x)))

A = [[2,-1,1],[2,2,2],[-1,-1,2]]
b = [-1,4,-5]
x = [[0, 0,0]]
MaxIter = 100
ErrorTable = [1]
ErrorRatio = [0]
eps = 10**(-7)
i = 1

while i <= MaxIter and abs(ErrorTable[i - 1]) > eps:
    xi = J(A, b, x[i - 1])
    x.append(xi)
    ei = np.linalg.norm(x[i] - x[i - 1], np.inf)  # /np.linalg.norm(x[i],np.inf)
    ErrorTable.append(ei)
    zi = np.linalg.norm(x[i] - x[i - 1], np.inf) / np.linalg.norm(x[i - 1] - x[i - 2], np.inf)
    ErrorRatio.append(zi)
    i += 1

print("Solution: Jacobi method")
'''
column 1: k (iteration step)
column 2: (1st component of computed solution vector at step k)
column 3: (2nd component of computed solution vector at step k)
column 4: (3rd component of computed solution vector at step k)
column 5: ke(k)k∞ (error norm at step k)
column 6: ke(k)k∞/ke(k−1)k∞ (ratio of successive error norms at step k)

'''
from tabulate import tabulate

table = []
for i in range(len(x)):
    table.append([i, x[i][0], x[i][1],x[i][2], ErrorTable[i], ErrorRatio[i]])

print(tabulate(table, headers=["k", "x1", "x2","x3", "ke(k)k∞", "ke(k)k∞/ke(k−1)k∞"]))


Solution: Jacobi method
  k             x1             x2             x3       ke(k)k∞    ke(k)k∞/ke(k−1)k∞
---  -------------  -------------  -------------  ------------  -------------------
  0       0               0             0              1                       0
  1      -0.5             2            -2.5            2.5                     1
  2       1.75            5            -1.75           3                       1.2
  3       2.875           2             0.875          3                       1
  4       0.0625         -1.75         -0.0625         3.75                    1.25
  5      -1.34375         2            -3.34375        3.75                    1
  6       2.17188         6.6875       -2.17188        4.6875                  1.25
  7       3.92969         2             1.92969        4.6875                  1
  8      -0.464844       -3.85938       0.464844       5.85938                 1.25
  9      -2.66211         2            -4.66211        5.85938      

In [37]:
from numpy import linalg
def GS(A, b, x):
  A = np.array(A)
  n = len(A)
  xnew = np.zeros(n)
  for i in range(n):
    xnew[i] = (b[i] - sum([A[i, j]*x[j] for j in range(i+1, n)]) - sum([A[i, j]*xnew[j] for j in range(i)]))/A[i, i]
  return xnew


b = [-1,4,-5]
x = [[0, 0,0]]
MaxIter = 100
ErrorTable = [1]
ErrorRatio =[0]
eps = 10**(-7)
i = 1

while i <= MaxIter and abs(ErrorTable[i - 1]) > eps:
  xi = GS(A, b, x[i - 1])
  x.append(xi)
 # ei = np.linalg.norm(x[i] - x[i - 1])/np.linalg.norm(x[i])
  ei=np.linalg.norm(x[i]-x[i-1],np.inf)#/np.linalg.norm(x[i],np.inf)
  ErrorTable.append(ei)
  zi = np.linalg.norm(x[i] - x[i - 1], np.inf) / np.linalg.norm(x[i - 1] - x[i - 2], np.inf)
  ErrorRatio.append(zi)
  i+=1
# Gause Seidel Solution
print("Solution: Gauss-Seidel method")
'''
column 1: k (iteration step)
column 2: (1st component of computed solution vector at step k)
column 3: (2nd component of computed solution vector at step k)
column 4: (3rd component of computed solution vector at step k)
column 5: ke(k)k∞ (error norm at step k)
column 6: ke(k)k∞/ke(k−1)k∞ (ratio of successive error norms at step k)

'''

from tabulate import tabulate

table = []
for i in range(len(x)):
    table.append([i, x[i][0], x[i][1],x[i][2], ErrorTable[i], ErrorRatio[i]])

print(tabulate(table, headers=["k", "x1", "x2","x3", "ke(k)k∞", "ke(k)k∞/ke(k−1)k∞"]))

Solution: Gauss-Seidel method
  k         x1       x2         x3      ke(k)k∞    ke(k)k∞/ke(k−1)k∞
---  ---------  -------  ---------  -----------  -------------------
  0   0         0         0         1                       0
  1  -0.5       2.5      -1.5       2.5                     1
  2   1.5       2        -0.75      2                       0.8
  3   0.875     1.875    -1.125     0.625                   0.3125
  4   1         2.125    -0.9375    0.25                    0.4
  5   1.03125   1.90625  -1.03125   0.21875                 0.875
  6   0.96875   2.0625   -0.984375  0.15625                 0.714286
  7   1.02344   1.96094  -1.00781   0.101562                0.65
  8   0.984375  2.02344  -0.996094  0.0625                  0.615385
  9   1.00977   1.98633  -1.00195   0.0371094               0.59375
 10   0.994141  2.00781  -0.999023  0.0214844               0.578947
 11   1.00342   1.99561  -1.00049   0.012207                0.568182
 12   0.998047  2.00244  -0.999756  0.